### PR TITLE
Divd 2021 00004 sheltervisible

### PR DESCRIPTION
**Pull request by Lennaert89**

### CODE REVIEW

**Comment by therealprocyon** [comment]
Er is een spelling error in bestandsnaam

**Review by therealprocyon — CHANGES_REQUESTED** [review]
Phising in title: moet phishing zijn.

**Review by therealprocyon — CHANGES_REQUESTED** [review]
Line 3 of the blog post contains `title: Phising slachtoffer notificatie / Victim notification phishing`

The right content for line 3 of the blog post would be: `title: Phishing slachtoffer notificatie / Victim notification phishing`

Also, the title of the blog post contains the same spelling error with regards to Phishing and Phising

**Review by therealprocyon — COMMENTED** [review]
It looks good for now 👍

**Review by MrSeccubus — APPROVED** [review]
Reviewed an added my changes

**Pull request merged**
